receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317

exporters:
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"

  jaeger:
    endpoint: "jaeger:14250"
    insecure: true

  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, zipkin, jaeger]
